export const FulllSiteLocators = {
    cookieAcceptButton: '#axeptio_btn_acceptAll',
    solutionsDropdown: '#w-dropdown-toggle-0',
    solutionMissionComptable: 'a[href="/mission-comptable"]',
    hubspotIframe: 'iframe[src*="forms"]',
    firstNameInput: 'input[name*="firstname"], input[name*="prenom"]',
    lastNameInput: 'input[name*="lastname"]',
    companyInput: 'input[name="company"], input[name*="societe"], input[name*="entreprise"]',
    jobTitleInput: 'input[name*="jobtitle"], input[name*="fonction"]',
    emailInput: 'input[name*="email"]',
    phoneInput: 'input[name="mobilephone"], input[name="phone"], input[type="tel"]',
    messageInput: 'textarea[name*="message"], textarea',
    numberOfUsersInput: '.hsfc-NumberInput input[inputmode="decimal"], input[inputmode="decimal"]',
    softwareUsedInput: 'input[name*="logiciel"]',
    detailOrigineInput: 'input[name*="detail_origine"]',
    projectTypeDropdown: '.hsfc-DropdownField:has(label:contains("Projet")) input[role="combobox"]',
    repriseDonneesDropdown: '.hsfc-DropdownField:has(label:contains("Reprise")) input[role="combobox"]',
    implementationTimeDropdown: '.hsfc-DropdownField:has(label:contains("Mise en place")) input[role="combobox"]',
    departmentDropdown: '.hsfc-DropdownField:has(label:contains("Département")) input[role="combobox"]',
    howKnownDropdown: '.hsfc-DropdownField:has(label:contains("Comment avez-vous connu")) input[role="combobox"]',
    submitButton: 'input[type="submit"], button[type="submit"]',
    dropdownOptionsList: '.hsfc-DropdownOptions__List__ListItem',
    dropdownSearchBox: 'input[role="searchbox"], input[placeholder="Rechercher"]',
    checkboxes: 'input[type="checkbox"]'
};
